APPID: "wxec760af73489c070"
APPSECRET: "08109283b680436fb9af185a677fb28c"
UserAppID: "18518286"
UserAppSecret: "Em8MNKmw"
WeatTemplateID: "emqjBE9tuRYwBOPvcGnRwVXxJ-7Z6xB2eO7DVXzg6pc"
WeatherVersion: "v1"