consulAddress: "localhost:28500"
local_port: 9100
#web_url: "0.0.0.0:30020"
#web_prefix: "/ywz"
registrationName: "base-linux-nodes"
#registrationID: "linux-node1"
#registrationTags:
#  - "prometheus1-30051"
#  - "prometheus2-30052"
#  - "prometheus3-30053"
